import { Router } from "express";
import { prisma, Prisma, ItemCategory, ItemUnit } from "@repo/database";
import { requireAuth } from "../middleware/requireAuth";
import { calculateStatus } from "../lib/status";

const router: Router = Router();

const VALID_CATEGORIES = new Set<string>(Object.values(ItemCategory));
const VALID_UNITS = new Set<string>(Object.values(ItemUnit));

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function toNonNegativeInt(value: unknown, fallback: number): number | null {
  if (value === undefined || value === null || value === "") {
    return fallback;
  }
  if (typeof value !== "number" || !Number.isInteger(value) || value < 0) {
    return null;
  }
  return value;
}

async function generateNextSku(): Promise<string> {
  const items = await prisma.item.findMany({
    select: { sku: true },
  });

  let maxNumber = 0;
  for (const { sku } of items) {
    const match = /^DCH(\d+)$/.exec(sku.trim());
    if (match) {
      const numeric = Number(match[1]);
      if (Number.isInteger(numeric) && numeric > maxNumber) {
        maxNumber = numeric;
      }
    }
  }

  return `DCH${maxNumber + 1}`;
}

async function createItem(
  data: Prisma.ItemCreateInput,
  autoGenerated: boolean,
): Promise<Awaited<ReturnType<typeof prisma.item.create>>> {
  for (let attempt = 0; attempt < 5; attempt += 1) {
    try {
      return await prisma.item.create({ data });
    } catch (error) {
      if (
        attempt < 4 &&
        autoGenerated &&
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === "P2002"
      ) {
        data.sku = await generateNextSku();
        continue;
      }
      throw error;
    }
  }
  throw new Error("Unable to generate a unique SKU");
}

router.get("/", requireAuth, async (req, res) => {
  const { category, filter } = req.query;

  if (
    category !== undefined &&
    (typeof category !== "string" || !VALID_CATEGORIES.has(category))
  ) {
    return res.status(400).json({ message: "Invalid category filter" });
  }

  if (
    filter !== undefined &&
    (typeof filter !== "string" ||
      !["expiring", "low-stock", "actions-needed"].includes(filter))
  ) {
    return res.status(400).json({ message: "Invalid filter" });
  }

  try {
    const now = new Date();
    const inThirtyDays = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

    const where: Prisma.ItemWhereInput = {};

    if (typeof category === "string") {
      where.category = category as ItemCategory;
    }

    if (typeof filter === "string") {
      const expiringCondition = {
        category: ItemCategory.CONSUMABLE,
        expiryDate: { gte: now, lte: inThirtyDays },
      };

      if (filter === "expiring") {
        Object.assign(where, expiringCondition);
      } else if (filter === "low-stock") {
        where.status = "Low";
      } else if (filter === "actions-needed") {
        where.status = "Action Required";
      }
    }

    const items = await prisma.item.findMany({
      where,
      orderBy: { createdAt: "desc" },
    });

    return res.json(items);
  } catch (error) {
    console.error("[Items] Failed to fetch items:", error);
    return res.status(500).json({ message: "Failed to fetch items" });
  }
});

router.get("/:id", requireAuth, async (req, res) => {
  try {
    const item = await prisma.item.findUnique({
      where: { id: req.params.id },
    });

    if (!item) {
      return res.status(404).json({ message: "Item not found" });
    }

    return res.json(item);
  } catch (error) {
    console.error("[Items] Failed to fetch item:", error);
    return res.status(500).json({ message: "Failed to fetch item" });
  }
});

router.post("/", requireAuth, async (req, res) => {
  const {
    sku,
    itemName,
    category,
    subCategory,
    brand,
    vendor,
    unit,
    openingStock,
    expiryDate,
  } = req.body ?? {};

  if (!isNonEmptyString(itemName)) {
    return res.status(400).json({ message: "Item name is required" });
  }
  if (typeof category !== "string" || !VALID_CATEGORIES.has(category)) {
    return res.status(400).json({ message: "A valid category is required" });
  }
  if (typeof unit !== "string" || !VALID_UNITS.has(unit)) {
    return res.status(400).json({ message: "A valid unit is required" });
  }

  const openingStockValue = toNonNegativeInt(openingStock, -1);
  if (openingStockValue === null || openingStockValue < 0) {
    return res.status(400).json({
      message: "Opening stock must be a non-negative integer",
    });
  }

  if (sku !== undefined && !isNonEmptyString(sku)) {
    return res
      .status(400)
      .json({ message: "SKU must be a non-empty string when provided" });
  }

  if (
    expiryDate !== undefined &&
    (typeof expiryDate !== "string" || Number.isNaN(Date.parse(expiryDate)))
  ) {
    return res.status(400).json({ message: "A valid expiry date is required" });
  }

  const isConsumable = category === ItemCategory.CONSUMABLE;
  const autoGenerated = !isNonEmptyString(sku);
  const resolvedSku = autoGenerated
    ? await generateNextSku()
    : sku.trim();

  const data: Prisma.ItemCreateInput = {
    sku: resolvedSku,
    itemName: itemName.trim(),
    category: category as ItemCategory,
    unit: unit as ItemUnit,
    openingStock: openingStockValue,
    currentStock: openingStockValue,
    availableStock: openingStockValue,
    status: calculateStatus(openingStockValue, openingStockValue),
    ...(isNonEmptyString(subCategory) ? { subCategory: subCategory.trim() } : {}),
    ...(isNonEmptyString(brand) ? { brand: brand.trim() } : {}),
    ...(isNonEmptyString(vendor) ? { vendor: vendor.trim() } : {}),
    ...(isConsumable && typeof expiryDate === "string"
      ? { expiryDate: new Date(expiryDate) }
      : {}),
  };

  try {
    const item = await createItem(data, autoGenerated);

    return res.status(201).json(item);
  } catch (error) {
    if (
      error instanceof Prisma.PrismaClientKnownRequestError &&
      error.code === "P2002"
    ) {
      return res.status(409).json({ message: "An item with this SKU already exists" });
    }
    console.error("[Items] Failed to create item:", error);
    return res.status(500).json({ message: "Failed to create item" });
  }
});

router.put("/:id", requireAuth, async (req, res) => {
  const { id } = req.params;
  const body = req.body ?? {};

  if (typeof id !== "string" || id.trim().length === 0) {
    return res.status(400).json({ message: "A valid item id is required" });
  }

  const existing = await prisma.item.findUnique({ where: { id } });
  if (!existing) {
    return res.status(404).json({ message: "Item not found" });
  }

  const data: Prisma.ItemUpdateInput = {};

  if (body.sku !== undefined) {
    if (!isNonEmptyString(body.sku)) {
      return res.status(400).json({ message: "SKU must be a non-empty string" });
    }
    data.sku = body.sku.trim();
  }

  if (body.itemName !== undefined) {
    if (!isNonEmptyString(body.itemName)) {
      return res.status(400).json({ message: "Item name must be a non-empty string" });
    }
    data.itemName = body.itemName.trim();
  }

  if (body.category !== undefined) {
    if (typeof body.category !== "string" || !VALID_CATEGORIES.has(body.category)) {
      return res.status(400).json({ message: "Invalid category" });
    }
    data.category = body.category as ItemCategory;
  }

  if (body.unit !== undefined) {
    if (typeof body.unit !== "string" || !VALID_UNITS.has(body.unit)) {
      return res.status(400).json({ message: "Invalid unit" });
    }
    data.unit = body.unit as ItemUnit;
  }

  for (const field of ["openingStock", "currentStock", "availableStock"] as const) {
    if (body[field] !== undefined) {
      const value = toNonNegativeInt(body[field], -1);
      if (value === null || value < 0) {
        return res
          .status(400)
          .json({ message: "Stock fields must be non-negative integers" });
      }
      data[field] = value;
    }
  }

  for (const field of ["subCategory", "brand", "vendor"] as const) {
    if (body[field] !== undefined) {
      if (typeof body[field] !== "string") {
        return res.status(400).json({ message: `${field} must be a string` });
      }
      data[field] = body[field] as string;
    }
  }

  if (body.expiryDate !== undefined) {
    if (typeof body.expiryDate !== "string" || Number.isNaN(Date.parse(body.expiryDate))) {
      return res.status(400).json({ message: "A valid expiry date is required" });
    }
    data.expiryDate = new Date(body.expiryDate);
  }

  if (Object.keys(data).length === 0) {
    return res.status(400).json({ message: "Nothing to update" });
  }

  const nextOpeningStock =
    body.openingStock !== undefined
      ? (data.openingStock as number)
      : existing.openingStock;
  const nextAvailableStock =
    body.availableStock !== undefined
      ? (data.availableStock as number)
      : existing.availableStock;
  data.status = calculateStatus(nextAvailableStock, nextOpeningStock);

  try {
    const item = await prisma.item.update({
      where: { id },
      data,
    });

    return res.json(item);
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      if (error.code === "P2025") {
        return res.status(404).json({ message: "Item not found" });
      }
      if (error.code === "P2002") {
        return res.status(409).json({ message: "An item with this SKU already exists" });
      }
    }
    console.error("[Items] Failed to update item:", error);
    return res.status(500).json({ message: "Failed to update item" });
  }
});

router.delete("/:id", requireAuth, async (req, res) => {
  try {
    await prisma.item.delete({
      where: { id: req.params.id },
    });

    return res.status(204).send();
  } catch (error) {
    if (
      error instanceof Prisma.PrismaClientKnownRequestError &&
      error.code === "P2025"
    ) {
      return res.status(404).json({ message: "Item not found" });
    }
    console.error("[Items] Failed to delete item:", error);
    return res.status(500).json({ message: "Failed to delete item" });
  }
});

export default router;
