export type CrmChecklistSection = {
  section: string;
  items: string[];
};

export const DEFAULT_CRM_CHECKLIST: CrmChecklistSection[] = [
  {
    section: "Client & WhatsApp Group",
    items: [
      "UPLOAD DETAILS ON WHATSAPP GROUP",
      "PC WILL ASSIGN CRM ON THE PROJECT",
      "CREATE THE CLIENT WHATSAPP GROUP USING THE CORRECT FORMAT",
      "ADD ALL RELEVANT TEAM MEMBERS TO THE GROUP",
      "SEND THE WELCOME MESSAGE TO THE CLIENT",
      "CREATE CRM SHEET WITH EXISTING DETAILS",
    ],
  },
  {
    section: "Liquor & Alcohol Requirements",
    items: [
      "HAVE YOU DISCUSSED LIQUOR LIST AND ITS BRANDS WITH CLIENT?",
      "IS ALCOHOL ALIGNED WITH EXPERIENTIAL STATIONS?",
      "IS THERE ANY JAPANESE ALCOHOL TO BE ADDED TO THE ALCOHOL LIST?",
      "SEND LIQUOR LIST TO CLIENT",
      "IS THERE ANY OTHER ALCOHOL SPECIFICALLY REQUIRED?",
      "SEND REQUIRED DETAILS MESSAGE IN THE GROUP",
      "SEND BEVERAGE/GLASSWARE REQUIREMENTS TO HOTEL",
      "IF BEVERAGE BY DCH - CHECK THIS",
      "IF GLASSWARE BY DCH - CHECK THIS",
    ],
  },
  {
    section: "Bar Requirements",
    items: [
      "CONFIRM CROWD SIZE AND SEND BAR REQUIREMENTS",
      "CONFIRM BAR SIZE WITH SITE MANAGER",
      "SEND TABLE REQUIREMENTS TO CLIENT",
      "CONFIRM BAR SET-UP TIMINGS",
    ],
  },
  {
    section: "Cocktail & Mocktail Menu",
    items: [
      "SEND DCH MASTER MENU FOR COCKTAILS SELECTION",
      "GET COCKTAILS & MOCKTAILS CONFIRMED",
      "CLIENT APPROVED THE FINAL NUMBER OF DRINKS?",
      "CONFIRM COUPLE INITIALS / HASHTAGS",
      "ASK IF THERE IS ANY THEME / LOGO",
      "ASK IF CLIENT LIKES CUSTOM-NAMED COCKTAILS",
    ],
  },
  {
    section: "Menu Information & Design",
    items: [
      "DID YOU RECEIVE COMPLETE INFORMATION FROM THE CLIENT?",
      "SEND FINAL COMPLETE INFORMATION TO DESIGNER",
      "ARE MENUS BEING SENT ON WHATSAPP FOR PREPARATION?",
      "FIRST DRAFT SHARED WITH CLIENT?",
      "CLIENT SHARED FEEDBACK / EDITS MADE?",
      "CLIENT APPROVED THE FINAL MENU?",
      "VERIFIED FOR GRAMMATICAL MISTAKES?",
      "SHARED FINAL MENU TO VENDOR WITH DEADLINE?",
      "CONFIRMED WHERE MENU WILL BE DELIVERED?",
      "MENUS PRINTED AND READY FOR DISPATCH 1 DAY BEFORE?",
      "REQUEST BRIDE & GROOM SHORT STORY / JOKES",
    ],
  },
  {
    section: "Client Follow-up",
    items: [
      "SEND A GENTLE REMINDER TO THE CLIENT WITH UPDATED CRM SHEET",
      "DIRECTOR TO PERSONALLY MESSAGE CLIENT",
    ],
  },
  {
    section: "Purchasing",
    items: [
      "SHARE POF WITH SITE MANAGER 1 DAY BEFORE",
      "ALL PURCHASING DONE?",
      "IF BARAAT YES - THEN PURCHASING DONE?",
    ],
  },
  {
    section: "MOM / Minutes of Meeting",
    items: [
      "CREATE CRM - MOM",
      "UPDATE MOM IN GROUP 1 DAY BEFORE THE EVENT",
      "VERIFY WITH GODOWN MANAGER IF ITEMS ARE AVAILABLE",
      "INFORM PURCHASE DEPT IF ITEM WAS NOT AVAILABLE",
    ],
  },
  {
    section: "Final Event Preparation",
    items: [
      "SHARE PDF TO SITE MANAGER 1 DAY BEFORE",
      "IF EVENT IS OUTSIDE DELHI, SHARE E-WAY BILL DETAILS",
      "SEND MOM + POF + MENU (ONE DAY BEFORE)",
      "CRM ENSURE MENU AND ALL REACHED TO SITE",
    ],
  },
];
